version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo "Building runtime versions..."
  build:
    commands:
      - echo "Zipping deployment package..."
      - zip -g deployment_package.zip lambda_function.py custom_encoder.py
  post_build:
    commands:
      - echo "Updating lambda function..."
      - aws lambda update-function-code --function-name products-lambda --zip-file fileb://deployment_package.zip
      - echo "DONE!!!"